### ISSUE TITLE
Only valid directives should propagate to editor

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/oide-slurm-assist#9] opened 2015-07-08 22:00 UTC
If a field is failing validation, it's value should not be propagated to the directives editor.

**Comment by kansuke231** [comment] 2015-07-13 19:58
It seems like that this issue is caused by the older version of AngularJS, namely ver 1.2, which is used in OIDE. With the latest AngularJS of version 1.4, this issue might be fixed without any trouble.

**Closed** 2015-07-14 17:43 UTC
Labels: bug, enhancement, help wanted
